'use client';

import { useEffect, useState } from 'react';
import { api } from '@/lib/api';
import { useRequireAuth } from '@/lib/useRequireAuth';
import { Skeleton, PageHeader } from '@/components/ui';
import type { CommitteeReport } from '@/lib/types';

interface Predictions {
  water: { history: number[]; avgDailyLitres: number; trend: string; projectedTankersPerWeek: number; recommendation: string };
}

export default function ReportsPage() {
  const { user } = useRequireAuth();
  const [report, setReport] = useState<CommitteeReport | null>(null);
  const [pred, setPred] = useState<Predictions | null>(null);

  useEffect(() => {
    if (!user) return;
    api<CommitteeReport>('/api/report').then(setReport).catch(() => {});
    api<Predictions>('/api/report/predictions').then(setPred).catch(() => {});
  }, [user]);

  if (!user) return null;

  return (
    <div className="py-6">
      <PageHeader
        title="Reports & predictions"
        subtitle="Auto-generated committee report and AI operations forecasts"
        action={<button onClick={() => window.print()} className="btn-ghost">🖨️ Print / PDF</button>}
      />

      {pred && (
        <div className="mt-5 card border-brand-200 p-5">
          <p className="text-xs font-bold uppercase tracking-wide text-brand-700">🔮 Predictive operations · water</p>
          <div className="mt-2 flex flex-wrap items-end gap-6">
            <div><p className="text-2xl font-bold text-ink-900">{pred.water.avgDailyLitres.toLocaleString('en-IN')} L</p><p className="text-xs text-ink-400">avg daily</p></div>
            <div><p className="text-2xl font-bold text-ink-900 capitalize">{pred.water.trend}</p><p className="text-xs text-ink-400">trend</p></div>
            <div><p className="text-2xl font-bold text-ink-900">{pred.water.projectedTankersPerWeek}</p><p className="text-xs text-ink-400">tankers/week</p></div>
          </div>
          <p className="mt-3 rounded-lg bg-brand-50 px-3 py-2 text-sm text-brand-800">{pred.water.recommendation}</p>
        </div>
      )}

      {!report ? <div className="mt-5"><Skeleton count={1} className="h-72" /></div> : (
        <div className="mt-5 card p-7">
          <div className="border-b border-ink-100 pb-4">
            <h2 className="text-xl font-bold text-ink-900">{report.societyName}</h2>
            <p className="text-sm text-ink-400">Committee report · {report.period}</p>
          </div>
          <p className="mt-4 rounded-xl bg-ink-50 p-4 text-ink-700">{report.summary}</p>
          <div className="mt-5 space-y-5">
            {report.sections.map((s) => (
              <div key={s.heading}>
                <h3 className="font-bold text-ink-900">{s.heading}</h3>
                <ul className="mt-1.5 space-y-1 text-sm text-ink-600">
                  {s.lines.map((l, i) => <li key={i} className="flex gap-2"><span className="text-brand-500">•</span> {l}</li>)}
                </ul>
              </div>
            ))}
          </div>
          <p className="mt-6 text-xs text-ink-400">Generated by NagarFix AI · {report.period}</p>
        </div>
      )}
    </div>
  );
}
